spring.application.name=02-spring-boot-rest-crud-employee



#
#JDBC properties
#
spring.datasource.url=jdbc:mysql://localhost:3306/employee_directory
spring.datasource.username=springstudent
spring.datasource.password=springstudent


#
# Configure custom path for Swagger
#
springdoc.swagger-ui.path=/my-ui.html


#
# cofigure custom path for api docs
#

springdoc.api-docs.path=/my-api-doc