#spring.application.name=mycoolapp

#Use wildcard "* " to expose all endpoints
#can also expose specific endpoints by listing them separated by commas


#management.endpoints.web.exposure.include=health,info
management.endpoints.web.exposure.include=*
management.info.env.enabled=true


#Exclude individual endpoints with a comma-delimited list
management.endpoints.web.exposure.exclude=health,info
info.app.name = My Super Cool App
info.app.description =This is A crazy fun app , Yeet!
info.app.version = 1.0.0



#
# Define my crazy properties
#
coach.name = Dr. Md Nakib Hayat Chowdhury
team.name = CSE Society BAUST


#
# Change Srping Boot embedded Tomcat server port
#
server.port = 7070

#
# set the context path or the applicaiton
# all requests will be prefixed with this path
#
server.servlet.context-path = /mycoolapp